### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by corneliusellen** [muuuydanny/mod_0_skills#1]
@muuuydanny Solid work on this. There are a few pieces of feedback we'd like you to implement. Please message me on Slack when you have done so or have any clarifying questions:
- Be consistent with writing how your methods modify attributes. For example, in class_1_example_object.txt the ```take_bite``` method should reassign your ```calories``` attribute to a new value, just like you wrote the method ```add_layer``` above it. Make sure this is consistent for all your methods.
- Your first class ```Sandwhich``` has ```current_layers``` listed and its instance does not. Each class and its instances should have the SAME attributes and methods.

**Comment by corneliusellen** [comment]
@muuuydanny Looks better, but you should not be using a hash rocket ```=>``` to reassign variables. You should be using an equal sign ```=```. So for example I would expect to see this for your method: 
```
take_bite: calories = 290
```

**Comment by muydanny** [comment]
@corneliusellen sounds good! I’ll put this in my notes. Thanks Ellen!
